previous.pdf: previous.tex usenix-*.tex tweetverif-USENIX.pdf tweetverif-SP.pdf
	pdflatex previous.tex

clean:
	-rm previous.aux
	-rm previous.log
	-rm previous.out
	-rm previous.pdf
	-rm previous.thm
	-rm previous.bbl
	-rm previous.blg
	-rm previous.brf
